version: "3"
services:
  web:
    build:
      context: ./
    ports:
      - "8080:80"
    volumes:
      - ./config/php/local.ini:/etc/php.d/40-local.ini
      - ./config/apache/local.conf:/etc/httpd/conf.d/local.conf
      - ./src:/var/www/virtual/default
    depends_on:
      - mysql
  mysql:
    image: "mysql:5"
    volumes:
      - ./config/mysql:/etc/mysql/conf.d
      - my_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: amazon_lamp
      MYSQL_DATABASE: amazon_lamp
      MYSQL_USER: amazon_lamp
      MYSQL_PASSWORD: amazon_lamp
volumes:
  my_data: {}
